tetrix:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  rightWheel_effort_controller:
    type: effort_controllers/JointPositionController
    joint: base_to_right_back_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}
  leftWheel_effort_controller:
    type: effort_controllers/JointPositionController
    joint: base_to_left_back_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}
